config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "home#index"

  resources :products do
    collection  do
        get :own_products
        get :buylists
      end
    resources :orders do
      member  do
        post :linerequest
        post :linerefund
      end
    end
  end

  get :confirm, to: "confirm#check"
end

app/models/order.rb
class Order < ApplicationRecord
  include Linepay

  belongs_to :product
  belongs_to :user

  validates :quantity, presence: true, numericality: { only_integer: true }

  after_create :set_order

  scope :created_desc, -> {order(id: :desc)}

  #state
  include AASM

  aasm column: :state do
    state :pending, initial: true
    state :confirmed, :refunded

    event :check do
      transitions from: :pending, to: :confirmed
    end

    event :cancel do
      transitions from: :confirmed, to: :refunded
    end
  end

  def set_confirm_data(response, current_user_id)
    self.transactionid = response["info"]["transactionId"]
    self.regkey = response["info"]["regKey"]
    self.buyer_id = current_user_id
    self.check
    self.save
  end

  def set_refund_data(response)
    self.refund_id = response["info"]["refundTransactionId"]
    self.refund_date = response["info"]["refundTransactionDate"]
    self.cancel
    self.save
  end

  private
  def set_order
    order_id = "order#{SecureRandom.uuid}"
    packages_id = "pack#{SecureRandom.uuid}"
    self.amount = self.quantity * self.product.price
    self.order_id = order_id
    self.packages_id = packages_id
    self.name = self.product.name
    self.price = self.product.price
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_order_product, except: [:linerequest]
  before_action :find_order, only: [:linerequest, :linerefund]
  after_action :send_refund_mail, only: [:linerefund]

  def index
    begin
      @orders = current_user.products.find(params[:product_id]).orders
    rescue
      redirect_to products_path
    end
  end

  def show
    @order = @product.orders.find(params[:id])
  end

  def create
    @order = @product.user.orders.create(order_params)
    if @order.save
      redirect_to product_order_path(@product, @order), notice: "Order was successfully created."
    else
      redirect_to products_path, notice: "建立失敗"
    end
  end

  def linerequest
    response = JSON.parse(@order.request_response.body)
    if response["returnMessage"] == "Success."
      redirect_to response["info"]["paymentUrl"]["web"]
    else
      redirect_to products_path
    end
  end

  def linerefund
    begin @order.buyer_id == current_user.id
      response = JSON.parse(@order.refund_response.body)
      if response["returnMessage"] == "Success."
        @order.set_refund_data(response)
        redirect_to product_order_path(@product, @order)
      else
        redirect_to product_order_path(@product, @order), data: { notice: "退款失敗" }
      end
    rescue
      redirect_to products_path, data: { notice: "???" }
    end
  end

  private
  def find_order_product
    @product = Product.find(params[:product_id])
  end

  def find_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.permit(:quantity, :product_id)
  end

  def send_refund_mail
    NotifyMailer.refund_owner_mail(@order).deliver_later
    NotifyMailer.refund_buyer_mail(@order).deliver_later
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def need_pay
    @order.pending?
  end

  def payed
    @order.confirmed?
  end

  def order_owner?
    @order.user == current_user
  end

  def order_buyer?
    @order.user != current_user
  end
end

app/views/orders/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <td>商品名稱</td>
      <td>訂單建立時間</td>
      <td>訂單總價</td>
      <td>商品數量</td>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order|%>
    <tr>
      <td><%= order.name %></td>
      <td><%= order.created_at&.strftime('%Y-%m-%d %H:%M') %></td>
      <td><%= order.amount %></td>
      <td><%= order.quantity %></td>
      <td><%= link_to "查詢訂單狀態", product_order_path(order.product, order) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/_state.html.erb
<div>
  <% if order_buyer? %>
    <% if need_pay %>
      <%= link_to "前往付款", linerequest_product_order_path, method: :post %>
    <% elsif payed %>
      <%= link_to "取消訂單並退款", linerefund_product_order_path, method: :post, data: { confirm: "退款後無法重複付款?!", "bootstrap-confirm": 'delete' } %>
    <% else %>
      此訂單無法異動。
    <% end %>
  <% end %>
</div>

app/views/orders/_turnback.html.erb
<div>
  <% if order_owner? %>
    <%= link_to "返回商品訂單列表", product_orders_path(@product) %><br>
  <% else order_buyer? %>
    <%= link_to "返回購買訂單區", buylists_products_path %>
  <% end %>
</div>

app/views/orders/index.html.erb
<h1>商品銷售狀況</h1>
<div>
  <%= link_to "返回商品資訊", product_path(@product) %>
</div>
<%= render "orders/index" %>

app/views/orders/show.html.erb
<br>
<h1><%= "#{@order.order_id}資訊" %></h1>
<br>
<div>
  <ul class="list-group">
    <small>購買商品</small>
    <li class="list-group-item"><%= @order.name %></li>
    <small>商品數量</small>
    <li class="list-group-item"><%= @order.quantity %></li>
    <small>訂單總價</small>
    <li class="list-group-item"><%= @order.amount %></li>
    <small>訂單狀態</small>
    <li class="list-group-item"><%= @order.state %></li>
  </ul>
</div>
<br>
<br>
<%= render 'state' %>
<br>
<%= render 'turnback' %>