config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "home#index"

  resources :products do
    collection  do
        get :own_products
        get :buylists
      end
    resources :orders do
      member  do
        post :linerequest
        post :linerefund
      end
    end
  end

  get :confirm, to: "confirm#check"
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true, numericality: { only_integer: true }
  validates :description, presence: true

  has_many :orders

  belongs_to :user
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :find_product, only: [:edit, :update, :destroy]

  def index
    @products = Product.all.includes([:user])
  end

  def buylists
    @orders = current_user.buylists.includes([:product]).created_desc
  end

  def own_products
    @products = current_user.products
  end

  def show
    begin
      @product = Product.find(params[:id])
      @order = current_user.buylists.new
    rescue
      redirect_to products_path
    end
  end

  def new
    @product = current_user.products.new
  end

  def create
    @product = current_user.products.new(product_params)
    if @product.save
      redirect_to product_path(@product), notice: "建立成功"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to product_path(@product), notice: "修改成功"
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path, notice: "刪除成功"
  end

  private
  def find_product
    begin
      @product = current_user.products.find(params[:id])
    rescue
      redirect_to products_path
    end
  end

  def product_params
    params.require(:product).permit(:name, :price, :description)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def owner?(product)
    product.user == current_user
  end

  def buyer?(product)
    product.user != current_user
  end
end

app/views/products/_form.html.erb
<br>
<br>
<div class="form-row">
  <%= form_for(product) do |form|%>
    <% if product.errors.any? %>
      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    <% end %>
    <%= form.label :name, "商品名稱" %>
    <div class="col">
      <%= form.text_field :name %>
    </div>
    <%= form.label :price, "商品價格" %>
    <div class="col">
      <%= form.text_field :price %>
    </div>
    <%= form.label :description, "商品描述" %>
    <div class="col">
      <%= form.text_area :description %>
    </div>
    <%= form.submit "送出" %>
  <% end %>
</div>

app/views/products/_index.html.erb
<br>
<br>
<br>
<table class="table">
  <thead>
    <tr>
      <td>商品名稱</td>
      <td>商品價格</td>
      <td>商品介紹</td>
      <td>前往購買</td>
      <td>編輯</td>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product|%>
    <tr>
      <td><%= product.name %></td>
      <td><%= product.price %></td>
      <td><%= product.description %></td>
      <% if buyer?(product)%>
        <td><%= link_to "GO!", product_path(product) %></td>
      <% else%>
        <td><%= link_to "檢視", product_path(product) %></td>
      <% end %>
      <% if owner?(product) %>
        <td><%= link_to "修改內容", edit_product_path(product) %></td>
        <td><%= link_to "刪除商品", product_path(product), method: :delete, data: {confirm: "確認刪除?", "bootstrap-confirm": 'delete' } %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/products/_productbuy.html.erb
<div>
  <% if buyer?(@product) %>
    <p>購買處</p>
    <%= form_tag product_orders_path(@product), method: :post do %>
      <%= label :quantity, "請選擇數量" %>
      <%= select_tag(:quantity, options_for_select([*1..10])) %> <br>
      <%= submit_tag "購買", name: nil, class: "btn btn-primary" %>
    <% end %>
  <% end %>
</div>

app/views/products/buylists.html.erb
<h1>購買訂單區</h1>
<%= render "orders/index", current_user: current_user %>
<%= link_to "返回商品列表", products_path %>

app/views/products/edit.html.erb
<br>
<h1> 修改商品 </h1>
<%= render 'form', product: @product %>
<br>
<%= link_to "返回商品列表", products_path %>

app/views/products/index.html.erb
<h1> 所有商品列表 </h1>
<%= render "index" %>
<%= link_to "個人商品", own_products_products_path %>
<br>
<br>
<%= link_to "個人購買紀錄", buylists_products_path %>

app/views/products/new.html.erb
<br>
<h1> 新增商品 </h1>
<br>
<%= render "form", product: @product %>
<br>
<%= link_to "返回商品列表", products_path %>

app/views/products/own_products.html.erb
<h1> 個人商品列表 </h1>
<%= render "index" %>
<%= link_to "新增商品", new_product_path %>
<br>
<br>
<%= link_to "返回所有商品", products_path %>

app/views/products/show.html.erb
<br>
<h1><%= "#{@product.name}資訊" %></h1>
<br>
<div>
  <ul class="list-group">
    <small>商品名稱</small>
    <li class="list-group-item"><%= @product.name %></li>
    <small>商品價格</small>
    <li class="list-group-item"><%= @product.price %></li>
    <small>商品簡介</small>
    <li class="list-group-item"><%= @product.description %></li>
  </ul>
</div>
<br>
<div><%= link_to "返回商品列表", products_path %></div><br>
<div>
  <% if owner?(@product) %>
    <%= link_to "商品訂單列表", product_orders_path(@product) %>
  <% end %>
</div>
<br>
<br>
<%= render 'productbuy' %>